project:
  type: website
  output-dir: docs
  
# Meta
description-meta: "Dr. Wei Fu is a health economist"
author-meta: "Wei Fu"

website:
  title: "Wei Fu"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - text: Research
        href: publications.qmd
#        menu:
#                - text: List of Publication
#                  href: publications.qmd
#                - text: Selected Papers
#                  href: posts.qmd#category=paper
#                - text: Commentary
#                  href: posts.qmd#category=commentary
#                - text: Awards
#                  href: posts.qmd#category=award  
#                - text: Grants
#                  href: https://deeppolicylab.github.io/projects.html
#                  target: _blank 
      - text: Grants
        href: grants.qmd
#      - text: Teaching
#        href: teaching.qmd


    right: 
      - text: CV
        href: files/Wei-Fu-CV.pdf
        target: _blank 
      - icon: github
        href: https://github.com/wef216
        target: _blank
#      - text: "{{< fa brands bluesky >}}"
#        href: https://bsky.app/profile/hegang.bsky.social
#        target: _blank
#      - icon: twitter-x 
#        href: https://twitter.com/DrGangHe
#        target: _blank        
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript

editor: visual

