---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: /custom.css
---

<!--Include academic icons or buttons-->

{{< include /files/includes/_academic.qmd >}}

My work has been published in the *Economic Journal*, *Journal of Public Economics*, *Journal of Health Economics*, *Journal of Population Economics*, *American Journal of Agricultural Economcis*, *Social Science & Medicine*, and *JAMA Network Open*.

You can find my recent [CV](files/Wei-Fu-CV.pdf){.external target="_blank"} and [Google Scholar](https://scholar.google.com/citations?user=m8-eoB8AAAAJ&hl=en) here.

```{=html}
<!--
   \[Econ\]: Economics journals; all authors are ordered alphabetically.\
   \[PH\]: Public health journals; all authors are ordered by contributions.\
   \[Med\]: Medical journals; all authors are ordered by contributions.\
 -->
```

<!-- - Total citations as of January 2025: -->

<!-- -   [Web of Science](https://www.webofscience.com/wos/author/record/N-4549-2013): 3,000 (h-index = 26)\  -->

<!-- -   [Google Scholar](https://scholar.google.com/citations?user=vf90AuEAAAAJ): 5,000 (h-index = 33, i10-index = 57) -->


Notes: \* corresponding author; <sup>+</sup> first author; <sup>++</sup> co-first author; <sup>GS</sup> graduate student advisee.   

### Substance Use
**Local problems, local solutions: Evidence from the Drug-Free Communities program on Youth Development**<br> 
         Shijun You, Wei Fu, and Shin-Yi Chou. 2025. <br>
         <u> *Submitted* </u>  <br>
         <font size="3"> [[NBER Working Paper No. 34182](https://www.nber.org/papers/w34182)]</font>

**Capping the First Script: Initial Opioid Prescription Limits and Intimate Partner Violence** <br>
         Wei Fu and Ashley C. Bradford. 2025 <br>
         <u> *R&R at Journal of Health Economics*</u>  <br>


**The Devastating Dance between Opioid and Housing Crises: Evidence from OxyContin Reformulation** <br>
         Ashley C. Bradford,  Wei Fu, and Shijun You. 2024 <br>
         <u> *Journal of Health Economics* </u> <br>
         <font size="3"> [[Published version](https://www.sciencedirect.com/science/article/abs/pii/S0167629624000754)]</font>


**Unemployment Insurance and Cigarette Smoking** <br>
         Wei Fu and Feng Liu. 2019 <br>
         <u> *Journal of Health Economics*</u> 63:34-51 <br>
         <font size="3"> [[Published version](https://www.nature.com/articles/s41467-023-40337-3)]</font>


### Health Care Utilization and Inequality
**Abortion, Economic Hardship, and Crime** <br>
         Erkmen G. Aslim, Wei Fu, Caitlin Myers, Erdal Tekin, and Bingjin Xue. 2025. <br>
         <u> *Submitted*</u>,  <br>
         <font size="3"> [[NBER Working Paper No. 30155](https://www.nber.org/papers/w30155)]</font>

**Proximity to Abortion Services and Child Maltreatment** <br>
         Aslim Erkmen, Wei Fu, and Erdal Tekin. 2025. <br>
         <u> *Submitted*</u>,  <br>
         <font size="3"> [[NBER Working Paper No. w32771](https://www.nber.org/papers/w32771)]</font>

**NIH Grant Expansion, Ancestral Diversity and Scientific Discovery in Genomics Research** <br>
         Wei Fu<sup>+</sup>, Shin-Yi Chou, and Li-San Wang. 2026.  <br>
         <u> Accepted, *Journal of Population Economic*</u>,  <br>
         <font size="3"> [[NBER Working Paper No. 30155](https://www.nber.org/papers/w30155)]</font>

**From Syringes to Dishes: Improving Food Security through Vaccination** <br>
         Erkmen G. Aslim, Wei Fu, Erdal Tekin, and Shijun You. 2025 <br>
         <u> *Journal of Public Economics*</u>  247:105392  <br>
         <font size="3"> [[Published version](https://www.sciencedirect.com/science/article/pii/S0047272725000908?utm_campaign=STMJ_219742_AUTH_SERV_PA&utm_medium=email&utm_acid=194150690&SIS_ID=&dgcid=STMJ_219742_AUTH_SERV_PA&CMX_ID=&utm_in=DM567183&utm_source=AC_)]  [[NBER WP 31025](https://www.nber.org/papers/w31045)]</font>

**State Vaccination Policies, Delayed Care, and Health Expenditures** <br>
         Erkmen G. Aslim, Wei Fu, Chia-Lun Liu, and Erdal Tekin. 2024 <br>
         <u> *Economic Journal*</u> 134(664):3096-136 <br>
         <font size="3"> [[Published version](https://academic.oup.com/ej/article/134/664/3096/7701410)]</font>

**A Single Dose For Me, A Wealth of Protection For Us: The Public Health Cost of Individualism in the Rollout of COVID-19 Vaccine** <br>
          Wei Fu<sup>+</sup>, Li-San Wang, and Shin-Yi Chou. 2024 <br>
         <u> *Social Science & Medicine*</u> 348:116849. <br>
         <font size="3"> [[Published version](https://www.sciencedirect.com/science/article/abs/pii/S0277953624002934)]</font>

**Reconcile the Debate Over Protective Effects of BCG Vaccine against COVID-19** <br>
         Wei Fu<sup>++</sup>, Pei-Chuan Ho, Chia-Lun Liu, Kai-Teh Tzeng, Nawar Nayeem, Jonni S. Moore, Li-San Wang, and Shin-Yi Chou. 2021. <br>
         <u> *Scientific Reports*</u> 11(1):8356  <br>
         <font size="3"> [[Published version](https://www.nature.com/articles/s41598-021-87731-9)]</font>


### Children and Female Wellbeing 
**Protecting Children through Paid Family Leave: Reduced Child Maltreatment in the Short- and Long-Run** <br>
         Wei Fu and Muzhe Yang. 2025.<br>
         <u> *Working Paper*</u>  <br>

**Homes in Limbo, Children at Risk: Exploring the Link between Housing Instability and Child Maltreatment Using the Discontinuity of the Protecting Tenants at Foreclosure Act** <br>
         Wei Fu and Muzhe Yang. 2025.<br>
         <u> *Working Paper*</u>  <br>

**The 2005 TennCare Disenrollments Increased Rates of Intimate Partner Violence: Insights for the Post-COVID Medicaid Unwinding** <br>
         Wei Fu<sup>+</sup>, Melissa B. Eggen, and Qi Zheng. 2025. <br>
         <u> *Health Services Research*</u> 20:e14647 <br>
         <font size="3"> [[Published version](https://onlinelibrary.wiley.com/doi/10.1111/1475-6773.14647?msockid=33ac7d22ec1b6b8a0c046e77ed746ab0)]</font>

**Migration Control Policy and Parent-Child Separation among Migrant Families: Evidence from China** <br>
         Yuanyuan Chen and Wei Fu. 2023.<br>
         <u> *Journal of Population Economics*</u> 36(4):2347-2388  <br>
         <font size="3"> [[Published version](https://link.springer.com/article/10.1007/s00148-023-00971-z)]</font>

**Unemployment Benefits, Food Insecurity, and Supplemental Nutrition Assistance Program Spending** <br>
         Wei Fu, Chen Huang and Feng Liu. 2023 <br>
         <u> *American Journal of Agricultural Economics*</u> 105(2):479-502 <br>
         <font size="3"> [[Published version](https://onlinelibrary.wiley.com/doi/full/10.1111/ajae.12322)]</font>

**Mental Distress Among Female Individuals of Reproductive Age and Reported Barriers to Legal Abortion Following the US Supreme Court Decision to Overturn Roe v Wade** <br>
         Dhaval Dave, Wei Fu, and Muzhe Yang. 2023. <br>
         <u> *JAMA Network Open*</u> 6(3):e234509-e234509 <br>
         <font size="3"> [[Published version](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2802750)]</font>


### Cognitive Function in Later-Life
**The Inclusion of ADRD Hierarchical Condition Category in Medicare Advantage Risk Adjustment Model is Associated with Improved Access to Healthcare** <br>
         Wei Fu<sup>+</sup>, Yuting Qian, Seyed Karimi, Hamid Zarei, and Xi Chen. 2025. <br>
         <u> *R&R at JAMA Network Open* </u>  <br>

**The Prediction of Alzheimer’s Disease through Multi-Trait Genetic Modeling** <br>
         Kaylyn Clark, Wei Fu<sup>++</sup>, Chia-Lun Liu, Pei-Chuan Ho, Hui Wang, Wan-Ping Lee, Shin-Yi Chou, Li-San Wang, Jung-Ying Tzeng. 2023. <br>
         <u> *Frontiers in Aging Neuroscience*</u> 15:1168638  <br>
         <font size="3"> [[Published version](https://www.frontiersin.org/articles/10.3389/fnagi.2023.1168638/full)]</font>

**Alzheimer’s Disease Variant Portal (ADVP): A Catalog of Genetic Findings for Alzheimer’s Disease** <br>
         Pavel P. Kuksa, Chia-Lun Liu, Wei Fu<sup>++</sup>, Liming Qu, Yi Zhao, Zivadin Katanic, Amanda B Kuzma, Pei-Chuan Ho, Kai-Teh Tzeng, Otto Valladares, Shin-Yi Chou, Adam C Naj, Gerard D Schellenberg, Li-San Wang, and Yuk Yee Leung. 2022.  <br>
         <u> *Journal of Alzheimer’s Disease* </u> 86:461–477 <br>
         <font size="3"> [[Published version](https://journals.sagepub.com/doi/full/10.3233/JAD-215055))]</font>




## Peer-Reviewed Chinese Journals

\[Econ\] Yuanyuan Chen and **Wei Fu**. 2023. Migration Control Policy in Megalopolis, School Enrollment Requirement and Children Left-behind. (特大城市人口调控政策、入学门槛与儿童留守). China Economic Quarterly (经济学(季刊)).

\[Econ\] Yuanyuan Chen and **Wei Fu**. 2017. Land Transfer Right, Rural-to-Urban Migration and Agricultural Production. (土地承包经营权流转、劳动力流动与农业生产). Management World (管理世界).

\[Econ\] Feng Huang and **Wei Fu**. 2017. Purchased by Government or Provided by Family? Estimating the Substitution Effects of Informal Care. (政府购买还是家庭照料? 基于家庭照料替代效应的实证分析). Nankai Economic Studies (南开经济研究).

\[Econ\] Zhaohua Li and **Wei Fu**. 2013. Ecological Footprint Analysis of the China’s International Trade. (中国进出口贸易内涵自然资本的生态足迹分析). China Industrial Economics (中国工业经济).
